### ISSUE TITLE
Security page:  'What is a public key pair?' breakout box is redundant

### ISSUE THREAD

**Issue by willfurnass** [arc-lessons/intro-hpc#8]

**Comment by james-grant1** [comment]
We felt that this was a useful addition to attempt to demystify:
1. what the key pair is 
2. why there are two of them and 
3. what each part does.  

Not necessarily resolved but by pulling it before `setting up an ssh key pair` perhaps this addresses makes it not redundant?

**Comment by willfurnass** [comment]
Still seems to be redundancy between 'What is a public key pair?' and the first para of 'Set up an SSH key pair protected by a passphrase' but given that it covers an important concept that may be new to many then reiteration may be a good thing.
